name: aop
author: vittorio ballestra <vittorio.ballestra@gmail.com>
description: aop framework for dart - aka, the final transformer
homepage: http://www.somewhere.yettobedecided.com
version: 0.0.1
dependencies:
  analyzer: '>=0.27.1 <0.28.0'

dev_dependencies:

  initialize: '>=0.6.2+1 <0.7.0'
  test: '>=0.12.10 <0.13.0'
  source_span: '>=1.2.1 <2.0.0'
  barback: '>=0.15.2+7 <0.16.0'
  source_maps: '>=0.10.1 <0.11.0'
  resource: '>=1.1.0 <2.0.0'
