name: aop
author: vittorio ballestra <vittorio.ballestra@gmail.com>
description: aop framework for dart - aka, the final transformer
homepage: http://www.somewhere.yettobedecided.com
version: 0.0.1
dependencies:
  analyzer: '>=0.27.1+2 <0.28.0'
